export const assets = {
    tension: 'assets/exported/tension.png',
    satisfaction: 'assets/exported/satisfaction.png',
    guitarist: 'assets/exported/cards/guitarist.png',
    basist: 'assets/exported/cards/basist.png',
    drummer: 'assets/exported/cards/drummer.png',
    keyboarder: 'assets/exported/cards/keyboarder.png',
    back: 'assets/exported/cards/back.png',
   
    field: 'assets/exported/backgrounds/field.png',
    hill: 'assets/exported/backgrounds/hill.png',
    mountain_low: 'assets/exported/backgrounds/mountain-low.png',
    mountain_high: 'assets/exported/backgrounds/mountain-high.png',
    atmosphere: 'assets/exported/backgrounds/atmosphere.png',
    earth: 'assets/exported/backgrounds/earth.png',
    sun: 'assets/exported/backgrounds/sun.png',
    space: 'assets/exported/backgrounds/space.png',
    galaxy: 'assets/exported/backgrounds/galaxy.png',
    cluster: 'assets/exported/backgrounds/cluster.png',
    creatures: 'assets/exported/backgrounds/creatures.png',
    cthulu: 'assets/exported/backgrounds/cthulu.png',
    universe: 'assets/exported/backgrounds/universe.png',
};
