export const assets = {
    tension: 'assets/exported/tension.png',
    satisfaction: 'assets/exported/satisfaction.png',
    
    guitar: 'assets/exported/cards/guitar.jpg',
    base: 'assets/exported/cards/base.jpg',
    drums: 'assets/exported/cards/drums.jpg',
    keyboard: 'assets/exported/cards/keyboard.jpg',
   
    field: 'assets/exported/backgrounds/field.jpg',
    hill: 'assets/exported/backgrounds/hill.jpg',
    mountains: 'assets/exported/backgrounds/mountains.jpg',
    atmosphere: 'assets/exported/backgrounds/atmosphere.jpg',
    earth: 'assets/exported/backgrounds/earth.jpg',
    sun: 'assets/exported/backgrounds/sun.jpg',
    space: 'assets/exported/backgrounds/space.jpg',
    galaxy: 'assets/exported/backgrounds/galaxy.jpg',
    cluster: 'assets/exported/backgrounds/cluster.jpg',
    creatures: 'assets/exported/backgrounds/creatures.jpg',
    cthulu: 'assets/exported/backgrounds/cthulu.jpg',
    azathoth: 'assets/exported/backgrounds/azathoth.jpg',
    simulation: 'assets/exported/backgrounds/simulation.jpg',
    computation: 'assets/exported/backgrounds/computation.jpg',
    simghosts: 'assets/exported/backgrounds/simghosts.jpg',
    simgod: 'assets/exported/backgrounds/simgod.jpg',
    simfractal: 'assets/exported/backgrounds/simfractal.jpg',
    fractal: 'assets/exported/backgrounds/fractal.jpg',
    mandala: 'assets/exported/backgrounds/mandala.jpg',
    mandalasculs: 'assets/exported/backgrounds/mandalasculs.jpg',
    devil: 'assets/exported/backgrounds/devil.jpg',
};
